name: Verify

on:
  push:
  pull_request:
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    runs-on: ubuntu-latest
    name: Check Syntax
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --no-interaction
      - name: Run PHP-CS-Fixer
        run: composer syntax:check

  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]
    name: Static Analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --no-interaction
      - name: Run PHPStan
        run: composer analyze:static